spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  config:
    import: classpath:SECRET.yml

server:
  port: 8090